name: Azure Web App Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Backend Docker image
      run: |
        docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/pet-flow-cloud-backend:latest ./backend/pet-flow-cloud

    - name: Build and push Frontend Docker image
      run: |
        docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/pet-flow-cloud-frontend:latest ./frontend/pet-flow-cloud-app

    - name: 'Deploy Backend to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME_BACKEND }}
        images: '${{ secrets.DOCKER_USERNAME }}/pet-flow-cloud-backend:latest'
        slot-name: 'production'
      env:
        AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME_BACKEND }}

    - name: 'Deploy Frontend to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME_FRONTEND }}
        images: '${{
